# -*- coding: utf-8 -*-
"""mask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmx4Scpg-A7OljQpBjM-ywBAl8Y9GRWF
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import random

#이미지가 paris_eval_gt에 있는 걸로 썼어요 :D
img = cv2.imread('/content/006_im.png')

mask_width = random.randint(50, img.shape[1] - 50)
mask_height = random.randint(50, img.shape[0] - 50)
mask_x = random.randint(0, img.shape[1] - mask_width)
mask_y = random.randint(0, img.shape[0] - mask_height)

mask = np.ones(img.shape[:2], np.uint8) * 255
cv2.rectangle(mask, (mask_x, mask_y), (mask_x + mask_width, mask_y + mask_height), 0, -1)

masked_img = cv2.bitwise_and(img,img,mask = mask)

cv2_imshow(masked_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
